фильтр на тип жилья
htmlacademy-javascript/1481739-keksobooking-22 pull request #11
Opened 2021-03-10 18:02 UTC by olga2102

2021-03-10 18:06 UTC, Shramkoweb requested changes

2021-03-10 18:06 UTC, Shramkoweb commented on js/main.js
> +// const OFFERS_COUNT = 10;
удалить

2021-03-10 18:06 UTC, Shramkoweb commented on js/map.js
> +const map = L.map('map-canvas');
А почему это стало снаружи?

2021-03-10 18:09 UTC, olga2102 commented on js/map.js
> +const map = L.map('map-canvas');
потому что создание маркеров снаружи, которые в мэп добавляются

2021-03-10 18:10 UTC, olga2102 commented on js/map.js
> +const map = L.map('map-canvas');
http://joxi.ru/5mdDw10c8zLQgm вот

2021-03-10 18:11 UTC, Shramkoweb commented on js/map.js
> +const map = L.map('map-canvas');
А причем маркеры к карте?
`const map = L.map('map-canvas');` это создание карты

2021-03-10 18:13 UTC, olga2102 commented on js/map.js
> +const map = L.map('map-canvas');
offerMarker.addTo(map).bindPopup(createCard(offer)); ну если я мэп внутри объявлю, как я снаружи оффермаркер в мэп засуну?

2021-03-10 18:23 UTC, olga2102 commented on js/map.js
> +const map = L.map('map-canvas');
мэп  в эдд ту  будет же нот дефайнд

2021-03-11 08:35 UTC, Shramkoweb approved these changes

2021-03-11 08:35 UTC, merged