Создала функции в js
htmlacademy-javascript/1481739-keksobooking-22 pull request #3
Opened 2021-01-31 11:46 UTC by olga2102

2021-01-31 14:26 UTC, Shramkoweb requested changes

2021-01-31 14:26 UTC, Shramkoweb commented on js/main.js
> +  }
Вот эти части у тебя повторяются в 2х функциях.

Проедлагаю под это сделать 2 функции еще отдельно и внутри их вызывать.

2021-01-31 14:26 UTC, Shramkoweb commented on js/main.js
> +    throw new Error('Диапазон должен принимать положительное значение');
А откуда ты узнала о `throw new Error` ?

2021-01-31 14:26 UTC, Shramkoweb commented on js/main.js
> +const getRandomInt = function (min, max, fix) {
`fix ` я бы сделал дефолтным например с `2`, чтобы по дофолту округлять всегда к 2 знакам?

2021-01-31 14:58 UTC, olga2102 commented on js/main.js
> +    throw new Error('Диапазон должен принимать положительное значение');
Гугл в помощь)) нужно ж было что то вместо консоль лог использовать. что нашла, то применила) не скажу, что сильно вникала, но вроде понятно) можно было проще?

2021-01-31 15:11 UTC, olga2102 commented on js/main.js
> +const getRandomInt = function (min, max, fix = 2) {
Я правильно поняла про дефолтное значение? поставить по умолчанию число?

2021-01-31 17:15 UTC, Shramkoweb commented on js/main.js
> +  if (RangeValidity) {
```suggestion
  if (RangeValidity(min, max)) {
```

2021-02-01 19:27 UTC, Shramkoweb approved these changes

2021-02-01 19:27 UTC, merged