Работает выбор случайного элемента массива, но не работает создание у…
htmlacademy-javascript/1481739-keksobooking-22 pull request #4
Opened 2021-02-07 19:04 UTC by olga2102

…никального массива

2021-02-07 21:54 UTC, Shramkoweb requested changes

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +const maxAvatarCount = 8;
Константы https://up.htmlacademy.ru/javascript/22/criteries#b7

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +];
```suggestion
const offerTitles = [
  'Лучшее, что ты видел',
  'Выгодное предложение',
  'Нормальный вариант',  
  'Закрой глаза и жми сюда',
  'Не для слабонервных',
];
```

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +const maxPrice = 100000;
Константы

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +const maxGuests = 30;
Константы

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +  'За чтооо',
Отфарматируй как ранее писал

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +  const indexElement = getRandomIntInclusive(0, elements.length-1)
```suggestion
  const indexElement = getRandomIntInclusive(0, elements.length - 1)
```

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +    uniqueArray.push(getRandomArrayElement)
Тут работает? Проверяла?

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +  const x = getRandomFloatInclusive (xMinLocation, xMaxLocation, 5);
Перед скобками вызова ф-и не нужны пробелы
```suggestion
  const x = getRandomFloatInclusive(xMinLocation, xMaxLocation, 5);
```

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +  return  {avatar: 'img/avatars/user' + 0 + getRandomIntInclusive(minAvatarCount, maxAvatarCount) + '.png'};
Автор - это строка. У тебя Обьект

Из задания: avatar, строка — адрес изображения вида img/avatars/user{{xx}}.png, где {{xx}} — это случайное число от 1 до 8 с ведущим нулём. Например, 01, 02 и т. д.

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +}
Это не нужно прям отдельно. Можно внутри getTotalObject поля author все это делать

2021-02-07 21:54 UTC, Shramkoweb commented on js/main.js
> +}
```suggestion
const getTotalObject = () => {
  return {
    author: getAuthor(),
    offer: {
       title: getRandomArrayElement (offerTitles),
    address: getLocation(),
    price: getRandomIntInclusive (minPrice, maxPrice),
    type: getRandomArrayElement (offerTypes),
    rooms: getRandomIntInclusive (minRooms, maxRooms),
    guests: getRandomIntInclusive (minGuests, maxGuests),
    checkin: getRandomArrayElement (offerCheckInTimes),
    checkout: getRandomArrayElement (offerCheckOutTimes),
    description: getRandomArrayElement (offerDescriptions),
    features: getUniqueArray (offerFeatures, 6),
    photos: getUniqueArray (offerPhotos, 3),
    },
    location: getLocation(),
  }
}
```

2021-02-08 16:42 UTC, olga2102 commented on js/main.js
> +  'За чтооо',
Не знаю, каким местом я смотрела, когда писала))

2021-02-08 17:04 UTC, olga2102 commented on js/main.js
> +  return  {avatar: 'img/avatars/user' + 0 + getRandomIntInclusive(minAvatarCount, maxAvatarCount) + '.png'};
Так написано: author, объект — описывает автора. Содержит одно поле:
avatar, строка — адрес изображения вида img/avatars/user{{xx}}.png, где {{xx}} — это случайное число от 1 до 8 с ведущим нулём. Например, 01, 02 и т. д.
Автор - объект.

2021-02-08 17:05 UTC, olga2102 commented on js/main.js
> +    uniqueArray.push(getRandomArrayElement)
не работает(( не понятно мне, почему

2021-02-08 17:37 UTC, Shramkoweb commented on js/main.js
> +    uniqueArray.push(getRandomArrayElement)
Ты плохо разобралось с темой функций. Попробуй еще раз разобраться с тем, что такое функция, а что такое вызов функции.

2021-02-08 17:39 UTC, Shramkoweb commented on js/main.js
> +  return  {avatar: 'img/avatars/user' + 0 + getRandomIntInclusive(minAvatarCount, maxAvatarCount) + '.png'};
Точно попутал с Аватар. Все ок

2021-02-08 17:42 UTC, olga2102 commented on js/main.js
> +    uniqueArray.push(getRandomArrayElement)
Мне кажется, я все материалы до дыр зачитала)) но че то у меня реально  с джс трабл. но я не сдаюсь)) пока. пошла читать дальше)

2021-02-08 17:51 UTC, Shramkoweb commented on js/main.js
> +    uniqueArray.push(getRandomArrayElement)
https://up.htmlacademy.ru/javascript/22/module/1/item/12

Там все есть

2021-02-09 13:50 UTC, Shramkoweb approved these changes

2021-02-09 13:50 UTC, Shramkoweb commented on js/main.js
> +const MAX_GUESTS  = 30;
Перед `=` лишний пробел

2021-02-09 13:50 UTC, Shramkoweb commented on js/main.js
> +    const randomElement = getRandomArrayElement(array);
👍

2021-02-09 13:50 UTC, Shramkoweb commented on js/main.js
> +const createSimilarOffers = new Array(TOTAL_COUNT).fill(null).map(() => getTotalObject());
Я бы `createSimilarOffers ` сделал функцией. Которая будет принимать количество обьявлений, которое нужно создать. И уже в нее передаешь `TOTAL_COUNT `

2021-02-09 13:50 UTC, merged