Создание попапа
htmlacademy-javascript/1481739-keksobooking-22 pull request #6
Opened 2021-02-17 20:22 UTC by olga2102

2021-02-18 07:37 UTC, Shramkoweb requested changes

2021-02-18 07:37 UTC, Shramkoweb commented on js/data.js
> +};
Таким образом ты могла сломать генерацию данных.

2021-02-18 07:37 UTC, Shramkoweb commented on js/data.js
> +};
Раньше у тебя был массив, а теперь объект.
Приводить palace -> Дворец надо было созданием еще одного объекта, а старый массив для данных не трогать

2021-02-18 07:37 UTC, Shramkoweb commented on js/data.js
> +const houseTypes = Object.keys(OFFER_TYPES);
Ага вижу, ты выкрутилась. Молодец, но лучше отсавить 2 отдельные сущности для двух разных задач.
Генерация данных и отображение карточек

2021-02-18 07:37 UTC, Shramkoweb commented on js/main.js
> +import './similar-elements.js';
Думаю у тебя не верные импорты, почитай, статьи что кинул в ТГ

2021-02-18 07:37 UTC, Shramkoweb commented on js/similar-elements.js
> +renderSimilarOffers(similarOffers);
Эту ф-ю лучше вызывать в корневом файле main

2021-02-18 07:37 UTC, Shramkoweb commented on js/similar-elements.js
> +renderSimilarOffers(similarOffers);
Внутри модулей только экспорт и определение ф-й

2021-02-20 22:33 UTC, Shramkoweb requested changes

2021-02-20 22:33 UTC, Shramkoweb commented on js/data.js
> +  'palace',
Сортировка - это хорошо)) Не забывай только это делать в начале ПР. Чтобы лишних правок не было

2021-02-20 22:33 UTC, Shramkoweb commented on js/data.js
> +  'palace',
👍

2021-02-20 22:33 UTC, Shramkoweb commented on js/main.js
> +const offersData = createSimilarOffers(1);
просто offers можно

2021-02-20 22:33 UTC, Shramkoweb commented on js/similar-elements.js
> +const HOUSES_TYPES = {
Это же словарь? Почитай https://up.htmlacademy.ru/javascript/22/criteries#b8

Там есть пример как именовать словари

2021-02-20 22:33 UTC, Shramkoweb commented on js/similar-elements.js
> +      }
Это вынеси в ф-ю.

2021-02-20 22:33 UTC, Shramkoweb commented on js/similar-elements.js
> +      }
В ф-ю

2021-02-20 22:33 UTC, Shramkoweb commented on js/similar-elements.js
> +
Лишний пробел

2021-02-20 22:33 UTC, Shramkoweb commented on js/util.js
> +    case 'src':
👍

2021-02-21 19:58 UTC, olga2102 commented on js/similar-elements.js
> +const HOUSES_TYPES = {
не уверена, что правильно назвала

2021-02-21 19:59 UTC, olga2102 commented on js/data.js
> +  'palace',
Я не очень поняла, что ты имеешь в виду)

2021-02-21 20:03 UTC, Shramkoweb approved these changes

2021-02-21 20:03 UTC, merged